### ISSUE TITLE
DNSSEC for subdomains?

### ISSUE THREAD

**Issue by alexcolb** [domainaware/checkdmarc#114]
Love the tool!

I'm wondering whether **dnssec** could be checked for subdomains too, instead of [just relying on the base domain's dnssec status](https://github.com/domainaware/checkdmarc/commit/6927490f62962e62d3fd2c7e16196076a26d02a6).

A use case here would be a subdomain zone that is delegated to another, untrusted name server. In these cases, dnssec works for the base domain, but should/will fail for the subdomain.

**Comment by seanthegeek** [comment]
I'm honestly not sure how to properly check for DNSSEC on subdomains.

If I comment out t[he line](https://github.com/domainaware/checkdmarc/blob/master/checkdmarc/dnssec.py#L44) that forces checking the base domain, the DNSSEC test returns `False` for `hq.dhs.gov`, even though the subdomain and base domain both pass [Verisign's DNSSEC test](https://dnssec-analyzer.verisignlabs.com/hq.dhs.gov).

**Comment by seanthegeek** [comment]
Fixed in 5.0.2
