### ISSUE TITLE
TLS/STARTTLS check malfunction

### ISSUE THREAD

**Issue by S1mple133** [domainaware/checkdmarc#138]
Hi!

While scanning the MX Domains of google.com with the command `checkdmarc google.com`, the output shows that starttls is not supported, as seen in the screenshot below

![image](https://github.com/domainaware/checkdmarc/assets/16444778/5acd7343-d24c-42cd-8cd5-a928b330ea7f)

Other online ssl-tools like [ssl-tools.net](https://ssl-tools.net/mailservers/google.com) show that starttls is supported on the `smtp.google.com` domain.

**Comment by BizzyBMW** [comment]
I have the same problem and I believe the issue is related to SSL certificate verification. I just ran a quick test by temporarily disabling hostname verification and certificate verification, and the result is correct.
