### ISSUE TITLE
BIMI marked as invalid when a= is included in the record.

### ISSUE THREAD

**Issue by richelo** [domainaware/checkdmarc#140]
Version: 5.3.1

This is the BIMI record:

v=BIMI1; l=https://amplify.valimail.com/bimi/time-warner/LFMoxJPK5xh-cable_news_network_inc2.svg; a=https://amplify.valimail.com/bimi/time-warner/LFMoxJPK5xh-cable_news_network_inc2.pem

valid=FALSE

error:

Error: Expected Regex at position 98 (marked with ➞) in: v=BIMI1; l=https://amplify.valimail.com/bimi/time-warner/LFMoxJPK5xh-cable_news_network_inc2.svg; ➞a=https://amplify.valimail.com/bimi/time-warner/LFMoxJPK5xh-cable_news_network_inc2.pem

This is a 100% valid BIMI record.

**Comment by seanthegeek** [comment]
Fixed
