### ISSUE TITLE
5.7.7, bimi logo and errors

### ISSUE THREAD

**Issue by Pascal76** [domainaware/checkdmarc#150]
Hello,

Just a question:

cases : 
1/ checkdmarc n1.e-nocibe.fr
2/ checkdmarc m11.email.samsung.com

Why don't you add a json['bimi']['image']**['errors']** for image issues
as you do with certificate issues with  json['bimi']['certificate']['validation_errors']  ?

Ex1:
- on json['bimi']['image']['errors'] 
"Unable to download https://www.nocibe.fr/bibliotheque/documents/bimi.svg - 400 Client Error: Bad Request for url: https://www.nocibe.fr/bibliotheque/documents/bimi.svg"
- on json['bimi']['warnings']
"Unable to download the logo" 

Ex2:
- on json['bimi']['image']['errors'] 
["The SVG version must be 1.2, not 1.1","The SVG base profile must be tiny-ps"]
- on json['bimi']['warnings']
"The logo does not respect the specifications" 

The goal is to be able to extract the error per type (certificate, image, ...)

**Comment by Pascal76** [comment]
Thank you @seanthegeek :)

**Comment by Pascal76** [comment]
json['bimi']['certificate']['error'] contains only 1 error even if it fails to download the pem file AND the logo file

**Comment by Pascal76** [comment]
more over you don't do exhaustive checks concerning the logo

ex: m11‍.‍email‍.‍samsung‍.‍com returns

      "validation_errors": [
        "The SVG version must be 1.2, not 1.1",
        "The SVG base profile must be tiny-ps"
      ]

BUT there are :      
. missing or empty 'baseProfile' attribute
. missing Title element
. not allowed 'x', 'y', 'overflow' attributes

(I don't know if you check the logo is a square too)

**Comment by seanthegeek** [comment]
A bug prevented the missing title error from deploying correctly. That has been fixed. Separate, more specific error messages are now used for a missing base profile vs the wrong base profile. It does not check that every part of `tiny-ps` is followed.

Here is what it checks for:

- The `l` value must be an HTTP URL
- The image must be a SVG file
- The image must have a base profile of `tiny-ps`
- The `svg` element must not include `x` or `y`
- The image must be square
- The image must not be larger than 32 KB

With the updated code, the BMI output for `m11‍.‍email‍.‍samsung‍.‍com` is:

```json
"bimi": {
    "record": "v=BIMI1; l=https://images.samsung.com/is/content/samsung/p5/ru/content/Samsung_wordmark.svg",
    "valid": true,
    "selector": "default",
    "tags": {
      "v": {
        "value": "BIMI1"
      },
      "l": {
        "value": "https://images.samsung.com/is/content/samsung/p5/ru/content/Samsung_wordmark.svg"
      }
    },
    "image": {
      "svg_version": "1.1",
      "width": 300.0,
      "height": 300.0,
      "filesize": "2.493 KB",
      "sha256": "c9056e31666d80bf61a13dc79bbaf8cd9337ec884beb57f5672ebbe468706e2e",
      "validation_errors": [
        "The SVG version must be 1.2, not 1.1",
        "The SVG is missing a base profile. It must have the base profile tiny-ps and conform to its standards. https://bimigroup.org/solving-svg-issues/",
        "The SVG must have a title element"
      ]
    },
    "warnings": [
      "Most providers will not display a BIMI image without a valid mark certificate"
    ]
  }
```
