### ISSUE TITLE
rua error

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#16]
Version 1.7.5 reports rua error on a domain like paypal.com

  "dmarc": {
    "record": "v=DMARC1; p=reject; rua=mailto:d@rua.agari.com; ruf=mailto:d@ruf.agari.com",
    "valid": false,
    "location": "paypal.com",
    "error": "mailto:d@rua.agari.com is not a valid DMARC report URI"
  }

However the auth record at rua.agari.com appears to be in place

iMac27:~ henj$ dig +short paypal.com._report._dmarc.rua.agari.com txt
"v=DMARC1"

**Comment by seanthegeek** [comment]
This was caused by a flaw in the regex I use for malto URIs. I didn't like the single char mailbox name in the email address.

This fix is included in the 1.7.8 release that I just pushed to PyPI.
