### ISSUE TITLE
dns_lookups for domains with failing SPF

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#18]
Hi 
It would be nice if domains with failing SPF could have "dns_lookups" set in the result.
Example: ebay.com

  "spf": {
    "record": "v=spf1 include:s._spf.ebay.com include:c._spf.ebay.com include:p._spf.ebay.com include:p2._spf.ebay.com ~all",
    "valid": false,
    "error": "Parsing the SPF record requires 11/10 maximum DNS lookups https://tools.ietf.org/html/rfc7208#section-4.6.4"
  },

**Comment by seanthegeek** [comment]
This will require a lot of refactoring, so moving this to milestone 2.1

**Comment by malvidin** [comment]
Is this complete?

**Comment by seanthegeek** [comment]
I still need to work on this one

**Comment by schack** [comment]
Yes.
elgiganten.dk
alka.dk
Many more domains with all sorts of SPF errors can be found here:
https://status.dmarc.dk/spf-defektlisten
(They all fail when usings Kittermans pyspf)

**Comment by malvidin** [comment]
Thanks you for the resources, I will see what I can do to help resolve this issue

**Comment by seanthegeek** [comment]
This has finally been implemented in `2.6.0`. Sorry it took so long!
