### ISSUE TITLE
External auth detection error

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#23]
Running checkdmarc on my domain dmarc.dk produces this error:
  "dmarc": {
    "record": "v=DMARC1; p=reject; rua=mailto:sh0izc5x@ag.dmarcian.com;",
    "valid": false,
    "location": "dmarc.dk",
    "error": "dmarcian.com does not indicate that it accepts DMARC reports about dmarc.dk - https://tools.ietf.org/html/rfc7489#section-7.1"
  }

However auth record at ag.dmarcian.com is in place:
iMac27:~ henj$ dig +short dmarc.dk._report._dmarc.ag.dmarcian.com txt
"v=DMARC1"

**Comment by seanthegeek** [comment]
Fixxed
