### ISSUE TITLE
DMARC record copy at root level results in no DMARC record at all

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#24]
A domain like danfoss.com has a copy of the DMARC record placed at the root of the domain.
This results in checkdmarc returning:
  "dmarc": {
    "record": null,
    "valid": false,
    "location": null,
    "error": "The DMARC record must be located at _dmarc.danfoss.com, not danfoss.com"
  }
While it's wrong to have a DMARC record at root level, it should not result in the real DMARC record being discarded

**Comment by seanthegeek** [comment]
I might get to this one this weekend
