### ISSUE TITLE
Missing source distribution on PyPI

### ISSUE THREAD

**Issue by Imxset21** [domainaware/checkdmarc#33]
This is as easy as `python3 setup.py sdist`, and is highly useful for vendored setups such as Facebook's.

**Comment by cooperlees** [comment]
I can elaborate a little more here to provide the context. At Facebook we block the use of wheels from external PyPI and build our own to avoid trusting random binaries from the Internet. This also allows us to link with our known good version of openssl and use our version of gcc etc. etc.

To do this, we use `pip wheel` to go and build within a chroot on our build servers. We rely on people having versioned `sdists` on PyPI for our normal mode of operation, but we also support `pip wheel` builds from Github directly, which @Imxset21 is using at the moment as a workaround for now, but we prefer to use released "versions" that are on PyPI for stability and reproducibility.

Thanks,
Cooper

**Comment by seanthegeek** [comment]
I have published source distributions for `checkdmarc` 2.5.1 and `parsedmarc` 3.7.1.

**Comment by seanthegeek** [comment]
@Imxset21 @cooperlees I'm curious, how are you making use of `checkdmarc` at Facebook?

**Comment by cooperlees** [comment]
Thanks!
