### ISSUE TITLE
checkdmarc.get_base_domain considers .test domains identical

### ISSUE THREAD

**Issue by Kagee** [domainaware/checkdmarc#39]
https://github.com/domainaware/checkdmarc/blob/1ccb575187ebbded606b322a2d048ff3264f720a/checkdmarc.py#L562

Because `.test` (and some other reserved domains) are not in the PSL, checkdmarc.get_base_domain considers all `*.test` domains equal.
 
This i.e means checkdmarc does not issue a warning on `_dmarc.nonauth-rua.invalid.test. 3600 IN TXT    "v=DMARC1; p=none; pct=100; rua=mailto:dmarc@noauth.valid.test"` even if `nonauth-rua.invalid.test._report._dmarc.noauth.valid.test.` is NXDOMAIN.

Suggestion: Add special case for .test

* RFC 2606 - Reserved Top Level DNS Names https://tools.ietf.org/html/rfc2606

**Comment by seanthegeek** [comment]
Fixed in 4.1.9
