### ISSUE TITLE
CLI: Options that take parameters makes the command fail if not followed by a non-parameter option

### ISSUE THREAD

**Issue by Kagee** [domainaware/checkdmarc#41]
When using options that take multiple parameters (i.e. -n and -o), checkdmarc errors out if the option is not followed by a no-parameter option. When followed by a no-parameter option, the command works as intended.
```
checkdmarc -v
4.1.9
```
### Example
```
checkdmarc -n 8.8.8.8 sol.no 2>&1 | grep 'checkdmarc: error' 
checkdmarc: error: the following arguments are required: domain
checkdmarc -n 8.8.8.8 --skip-tls sol.no 2>&1 | grep 'checkdmarc: error'

checkdmarc -o sol.no.json sol.no 2>&1 | grep 'checkdmarc: error' 
checkdmarc: error: the following arguments are required: domain
checkdmarc -o sol.no.json --skip-tls sol.no 2>&1 | grep 'checkdmarc: error'
```

**Comment by seanthegeek** [comment]
This seems to be an issue with Python's argparse module, not a bug in checkdmarc itself.

**Comment by Kagee** [comment]
Hmm, i see. Looks like there are no pretty solutions, only input workarounds. To bad.
`checkdmarc -n 8.8.8.8 --skip-tls sol.no`
`checkdmarc sol.no -n 8.8.8.8`
`checkdmarc -n 8.8.8.8 -- sol.no`

**Comment by knoepfchendruecker** [comment]
The long-form options (--output=, --nameserver=) are an effective workaround:

`checkdmarc --skip-tls --nameserver=8.8.8.8 --output=sol.csv sol.no`
