### ISSUE TITLE
checkdmarc certificate test doesn't follow redirects

### ISSUE THREAD

**Issue by rotten** [domainaware/checkdmarc#43]
```
"warnings": [
      "my.domain.com: SSL error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:847)"
    ]
```

We have a certificate set up with send-in-blue.  ( https://www.sendinblue.com/ )

They automatically redirect from "my.domain.com" to "r.my.domain.com", this redirect causes the above certificate verification to fail checkdmarc's test.

If most mail clients will follow redirect to validate the certificate then this is ok and checkdmarc should follow the redirect as well.

However, if the redirect is actually rendering this certificate as useless, I'd like to let send-in-blue know.   I don't see anything in python smtplib documentation that indicates it should follow a redirect.

**Comment by seanthegeek** [comment]
CheckDMARC checks TLS certs on mail servers, which are not affected by HTTP redirects that you may have on your HTTPS server.

Without knowing the actual domain, it's hard to say why it is failing.

**Comment by rotten** [comment]
I'm happy to PM the domains if that will help.   I'm not sure the best way to PM you though.  You can try emailing me - I believe I have at least one contact exposed in my github profile.

**Comment by seanthegeek** [comment]
I sent an email to the Gmail address listed in your Github profile.

**Comment by seanthegeek** [comment]
Resolved via email
