### ISSUE TITLE
Add support for DNSSEC

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#44]
Would it be possible to add a DNSSEC check?

**Comment by seanthegeek** [comment]
Based on this is seems like to it too complex for me to properly implement https://stackoverflow.com/a/55408918/501333

**Comment by schack** [comment]
Are you sure it's as complicated as he makes it?
Using the "let the resolver do the heavy lifting" approach and assuming we trust the resolver we are using, it's sort of simple.
Using dig
dig schack.dk ns +dnssec

if the zone is signed properly, the "ad" flag will be set:
flags: qr rd ra ad;
and a RRSIG will be present

In Python it would be something like:
def dnssec_supported(domain):
    try:
        request = dns.message.make_query(domain, dns.rdatatype.NS, want_dnssec=True)
        response = dns.query.udp(request, DNSSERVERS[0], timeout=12)
    except Exception as e:
        return False
    for record in response.answer:
        if record.rdtype == dns.rdatatype.RRSIG  and (response.flags & dns.flags.AD):
            return True
    return False

**Comment by seanthegeek** [comment]
That is very helpful. Thanks! I'll look into it more.

**Comment by seanthegeek** [comment]
Added in 4.2.0 :)
