### ISSUE TITLE
Garbage after all mechanism causes an exception

### ISSUE THREAD

**Issue by schack** [domainaware/checkdmarc#45]
Example:
avd.dk returns the following TXT record.
"v=spf1 mx a ip4:213.5.39.110 a:navsmtpsrv001.bodata.dk ?all MS=83859DAEBD1978F9A7A67D3A0A483D6F5EB88784"
and causes an exception.
Section 5.1 in the spec states:
   Mechanisms after "all" will never be tested.  Mechanisms listed after
   "all" MUST be ignored.  Any "redirect" modifier (Section 6.1) MUST be
   ignored when there is an "all" mechanism in the record, regardless of
   the relative ordering of the terms.

**Comment by seanthegeek** [comment]
Fixed in 4,2,0
