### ISSUE TITLE
BIMI support

### ISSUE THREAD

**Issue by Cyb0rg42** [domainaware/checkdmarc#58]
In the source code I see that there is support for BIMI records. In the json that is produced there is no BIMI information. Is it true that BIMI is not yet fully implemented?

**Comment by seanthegeek** [comment]
Hi, BIMI support is not fully implemented yet. I'd like to add checks for image file types and dementions before I add the BIMI results to the output, I'm just haven't had the time to do it.

**Comment by EmailKarma** [comment]
It would be nice to see the resulting DNS records even without the validation... this might be a useful resource for validation testing though: https://github.com/marcbradshaw/bimi-validator or this: https://github.com/pepipost/BIMI-official

**Comment by seanthegeek** [comment]
Added in 5.0.0

**Comment by EmailKarma** [comment]
Is there a command line flag that would be required to have the BIMI record shown? I'm not seeing it in the output file when using '-o output.csv' options in version 5.2.0.

**Comment by seanthegeek** [comment]
You need to supply the bimi selector with the -b flag. Technically the RFC specifies a default selector, but I don't want to assume a domain isn't using BIMI just because it is using a different selector. From what I've seen from major brands the default selector is rarely used for some reason.

**Comment by EmailKarma** [comment]
Got it thanks.
