### ISSUE TITLE
how to run from a .py script

### ISSUE THREAD

**Issue by sdebarun** [domainaware/checkdmarc#60]
Hi, 
I'm completely new in python and is trying to get the code run from within a .py script. something like this
```
 import checkdmarc
 def dmarc():
 	return checkdmarc fbi.gov
 dmarc();	
```

I am trully sorry if that is a silly question as I do not know how to do it. I am trying the code but it gives me a syntax error.
```

 return checkdmarc "fbi.gov"
                      ^
SyntaxError: invalid syntax
```

can anyone help or point me to some direction? 
Thanks,

**Comment by sdebarun** [comment]
found a way to achieve what I wanted too 
```
import os
os.system('checkdmarc mailkit.com')
```
but is it a good way to do it? 
Also I need to loop through and reoraganize the json as per my need from the uotput. How do I do that?

**Comment by seanthegeek** [comment]
use checkdmarc.check_domains

https://domainaware.github.io/checkdmarc/checkdmarc.html#checkdmarc.check_domains
