### ISSUE TITLE
Feature Request - SPF Record check of parent domain if given domain has no SPF record

### ISSUE THREAD

**Issue by definity** [domainaware/checkdmarc#65]
If a given domain does not have an SPF record, have a command-line option that would support checking the parent domain for an SPF record and report results.  In other words, if there's no SPF record for the given domain, try the parent.  If the parent has a SPF record, use that.

**Comment by schack** [comment]
Why that? SPF records are not inherited from parent domain

**Comment by seanthegeek** [comment]
Closing because SPF records are not inherited from parent domain as a part of the standard.
