### ISSUE TITLE
_query_dns doesnt use all nameservers in the list

### ISSUE THREAD

**Issue by thesyst** [domainaware/checkdmarc#67]
If you list several servers in '_nameservers_' argument of any function (for example '_check_domains_') and the first server on the list won't answer during timeout, '_dns.exception.Timeout_' will be raised. 
No other servers on the list will have a chance to process this query, only the first one will.

Example (first server was made incorrect intentionally):

    result = checkdmarc.get_spf_record('google.com', nameservers=['8.8.8.81', '8.8.8.8'])

**Comment by seanthegeek** [comment]
This was fixed in a previous release
