### ISSUE TITLE
query_spf_record doesn't raise MultipleSPFRTXTRecords exception

### ISSUE THREAD

**Issue by thesyst** [domainaware/checkdmarc#68]
If a domain has multiple spf-records, function _query_spf_record_ correctly figuring this out, but fails to raise _MultipleSPFRTXTRecords_ exception, raising _SPFRecordNotFound_ instead.

Also, there is no mentioning in the documentation that any of spf-related functions could raise _MultipleSPFRTXTRecords_ exception.

**Comment by seanthegeek** [comment]
Turns out this was fixed ages ago.
