### ISSUE TITLE
DMARC fo=0:1; is valid

### ISSUE THREAD

**Issue by dodge107** [domainaware/checkdmarc#71]
We have a record that has the following:

fo=0:1:d:s;   

This causes DMARC to be invalid 

 "error" : "fo DMARC tag options 0 and 1 are mutually exclusive"

From the RFC this is valid, you just want all permutations of the report:

   0: Generate a DMARC failure report if all underlying
         authentication mechanisms fail to produce an aligned "pass"
         result.

  1: Generate a DMARC failure report if any underlying
         authentication mechanism produced something other than an
         aligned "pass" result.

**Comment by Kagee** [comment]
While I concurr that the RFC appears to not exclude both 0&1, as I read them, if you have 1, setting 0 will not give you any more reports, as a report that has *all* non-pass, will match the *any* non-pass of the 1-setting?
