### ISSUE TITLE
The SPFSyntaxError exception isn't raised when text after "all" tag exists

### ISSUE THREAD

**Issue by stereohj** [domainaware/checkdmarc#73]
Hello!
When is used the parse_spf_record (or check_domains) function with an spf record value with text after "all" tag, SPFSyntaxError Exception isn't being raised.

**Comment by Pascal76** [comment]
The same when there is a redirect before an other mechanism
ex: v=spf1 redirect=__spf.campaign.adobe.com ip4:151.106.144.120
It should return a warning like:  The modifiers ('redirect=__spf.campaign.adobe.com') should be after all the mechanisms

**Comment by seanthegeek** [comment]
Anything treated after the `all` mechanism is ignored according to the RFC. It is atted as a warning, not an exception or error, because the previous half of the record is still usable.

**Comment by Pascal76** [comment]
and what about my message @seanthegeek ?
