### ISSUE TITLE
get_spf_record fails when SPF record uses macros

### ISSUE THREAD

**Issue by richardmhope** [domainaware/checkdmarc#81]
A SPFRecordNotFound is raised when the SPF record uses macros e.g.

`checkdmarc.SPFRecordNotFound: The domain %{ir}.%{v}.%{d}.spf.has.pphosted.com does not exist`

**Comment by trolldbois** [comment]
same with agari.com
"record": "v=spf1 exists:%{i}._i.%{d}._d.espf.agari.com include:%{d}.01.spf-protect.agari.com include:mktomail.com -all",

**Comment by seanthegeek** [comment]
Fixed in 4.8.0.
