### ISSUE TITLE
Problem with unrelated DMARC records

### ISSUE THREAD

**Issue by kazet** [domainaware/checkdmarc#91]
If DMARC for a domain contains an unrelated record, UnrelatedTXTRecordFoundAtDMARC gets raised and that prevents checkdmarc from finding a correct DMARC record.

Correct behavior would be reporting the unrelated TXT record as a warning and then proceeding to obtain the DMARC record.

**Comment by seanthegeek** [comment]
Made this check optional in the API with version 4.8.0.
